### ISSUE TITLE
This mod fails to load in any forge version from 1.17.1-37.0.21 and below. Suggest you update to 37.0.24 or 25.

### ISSUE THREAD

**Issue by ExiledMiner04** [DrunkBlood/Lucky-Ore#1]
Image link to the error handler in the game itself.
https://imgur.com/EaEXtJc

**Comment by ExiledMiner04** [comment]
May need to update for forge 37.0.31 now, they changed how tools work and many other things.

**Comment by DrunkBlood** [comment]
Since forge does not support old versions and I tested with 37.0.58. The tool change was already in the first 1.17 release
