### ISSUE TITLE
Lucky Ores don't seem to interact with Andesite

### ISSUE THREAD

**Issue by AngleWyrm10** [DrunkBlood/Lucky-Ore#4]
Hey, love this mod. If you ever decide to make an update for it, I've noticed that in my world the Lucky Ore that spawned in a cavern full of Andesite doesn't seem to create new ore blocks nearby.

It does work near other types of stone though.
v1.1.0 for MC 1.18.2

**Comment by DrunkBlood** [comment]
check out the new variants in the 1.19 update. I added variants for all vanilla ore types in Andersite, Granite and Diorite
